version: '3'
services:
    express-typescript:
        build:
            context: .
            dockerfile: ./local.Dockerfile
        container_name: 'to00bs65-3001-guestbook'
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev"
        ports:
            - 4040:4040
            - 5550:5550
