name: Deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "laurea-guestbook"
          heroku_email: "zilahi@gmail.com"
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production